apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
subsets:
  - addresses:
      # If you want to use a mysql running on your host machine get the host.minikube.internal
      # > minikube ssh
      # > dig host.minikube.internal
      # SERVER would change depends on your VM driver.
      - ip: 192.168.49.1
    ports:
      - port: 3306