apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-auth-backend
spec:
  selector:
    matchLabels:
      app: rabbitmq-auth-backend
  template:
    metadata:
      labels:
        app: rabbitmq-auth-backend
    spec:
      containers:
      - name: rabbitmq-auth-backend
        image: coches/rabbitmq-auth-backend
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        envFrom:
          - configMapRef:
              name: rabbitmq-auth-backend-config
          - secretRef:
              name:  rabbitmq-auth-backend-secret
            
