kind: Service
apiVersion: v1
metadata:
  # namespace: test-rabbitmq
  name: rabbitmq
  labels:
    app: rabbitmq
    type: LoadBalancer
spec:
  type: NodePort
  ports:
   - name: http
     protocol: TCP
     port: 15672
     targetPort: 15672
     nodePort: 31672
   - name: amqp
     protocol: TCP
     port: 5672
     targetPort: 5672
     nodePort: 30672
  #  - name: mqtt
  #    protocol: TCP
  #    port: 1883
  #    targetPort: 1883
  #    nodePort: 32672
  #  - name: ws
  #    protocol: TCP
  #    port: 15675
  #    targetPort: 15675
   - name: ws-stomp
     protocol: TCP
     port: 15674
     targetPort: 15674
  selector:
    app: rabbitmq

